/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancarios;

import java.awt.BorderLayout;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author nicolas
 */
public class registro_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Opciones_pago
     */
    public registro_usuarios() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_contra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etiqueta_nombre = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        etiqueta_apellido = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        etiqueta_estado = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        etiqueta_cargo = new javax.swing.JLabel();
        combo_cargo = new javax.swing.JComboBox<>();
        etiqueta_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        etiqueta_contraseña = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txt_CVU = new javax.swing.JTextField();
        bton_registar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jLabel1.setText("exitoooo");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, -1));

        etiqueta_nombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_nombre.setText("Nombre");
        jPanel2.add(etiqueta_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 300, -1));

        etiqueta_apellido.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_apellido.setText("Apellidos");
        jPanel2.add(etiqueta_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));
        jPanel2.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 300, -1));

        etiqueta_estado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_estado.setText("Estado civil");
        jPanel2.add(etiqueta_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Casado", "Soltero" }));
        jPanel2.add(combo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        etiqueta_cargo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_cargo.setText("Tarjeta");
        jPanel2.add(etiqueta_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        combo_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Visa", "Mastercard" }));
        jPanel2.add(combo_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));

        etiqueta_email.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_email.setText("Email");
        jPanel2.add(etiqueta_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, -1));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 300, -1));

        etiqueta_contraseña.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiqueta_contraseña.setText("Crear contraseña");
        jPanel2.add(etiqueta_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 120, -1));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("CVU:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        jPanel2.add(txt_CVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        bton_registar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bton_registar.setText("Registrar usuario");
        bton_registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_registarActionPerformed(evt);
            }
        });
        getContentPane().add(bton_registar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void bton_registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_registarActionPerformed
        conexion.coneccion cs = new conexion.coneccion();
           
         String consulta = "insert into datos_bancarios(nombre,apellido,estado_civil,cargo,email,contraseña,CVU)values(?,?,?,?,?,?,?)";
        String nombres = txt_nombres.getText();
        String apellidos = txt_apellidos.getText();
        String contraseña = txt_password.getText();
        String email = txt_email.getText();
        String comboEstado = combo_estado.getSelectedItem().toString();
        String CVU= txt_CVU.getText();
        String comboCargo = combo_cargo.getSelectedItem().toString();
        
        if (nombres.isEmpty() || apellidos.isEmpty() || contraseña.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "COMPLETAR DATOS ");
        } else {
            
            if (comboEstado.equalsIgnoreCase("Seleccionar")) {
                JOptionPane.showMessageDialog(null, "INGRESE ESTADO CIVIL ");
            }
            
            if (comboCargo.equalsIgnoreCase("Seleccionar")) {
                JOptionPane.showMessageDialog(null, "INGRESE EL TIPO DE TARJETA");
            } else {
               
                try {
                   
                    
                   CallableStatement ps= cs.ConectarBd().prepareCall(consulta);
                   // Establecer los valores de los parámetros
            ps.setString(1, nombres);
            ps.setString(2, apellidos);
            ps.setString(3, comboEstado);
            ps.setString(4, comboCargo);
            ps.setString(5, email);
            ps.setString(6, contraseña);
            ps.setString(7, CVU);   
             ps.executeUpdate();
            limpiar(); 
            
                    JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS NUEVO PERFIL CREADO");
                    
                } catch (Exception e) {
                    
                    JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR" + e);
                    
                }finally {
            // Cerrar los recursos
            try {
               
                if (cs != null) cs.ConectarBd().close();
            } catch (Exception e) {
                // Manejar errores de cierre de recursos
                JOptionPane.showMessageDialog(null, "ERROR AL CERRAR RECURSOS: " + e.getMessage());
            }
                
                
            }
            
        }
        
        }
        

    }//GEN-LAST:event_bton_registarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       bancarios.Inicio_sesion inicio = new bancarios.Inicio_sesion();
       inicio.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bton_registar;
    private javax.swing.JComboBox<String> combo_cargo;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JLabel etiqueta_apellido;
    private javax.swing.JLabel etiqueta_cargo;
    private javax.swing.JLabel etiqueta_contraseña;
    private javax.swing.JLabel etiqueta_email;
    private javax.swing.JLabel etiqueta_estado;
    private javax.swing.JLabel etiqueta_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_CVU;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

   void limpiar(){
   txt_nombres.setText("");
   txt_apellidos.setText("");
   combo_estado.setToolTipText("");
   combo_cargo.setToolTipText("");
   txt_email.setText("");
   txt_password.setText("");
   txt_CVU.setText("");
   }
}
