/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancarios;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author nicolas
 */
public class transferencia_Mail extends javax.swing.JFrame {

    /**
     * Creates new form transferencia_Mail
     */
    public transferencia_Mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        txt_montomail = new javax.swing.JTextField();
        bton_confirmar = new javax.swing.JButton();
        bton_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Mail:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Monto:");

        bton_confirmar.setText("confirmar");
        bton_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_confirmarActionPerformed(evt);
            }
        });

        bton_salir.setText("Salir");
        bton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bton_confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bton_salir)
                                .addGap(0, 463, Short.MAX_VALUE))
                            .addComponent(txt_montomail))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_montomail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bton_confirmar)
                    .addComponent(bton_salir))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_salirActionPerformed
       bancarios.Pagina_principal principal = new bancarios.Pagina_principal();
       principal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bton_salirActionPerformed

    private void bton_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_confirmarActionPerformed
        try {
            this.transferir_dinero(txt_mail, txt_montomail);
        } catch (SQLException ex) {
            Logger.getLogger(transferencia_Mail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bton_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferencia_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferencia_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferencia_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferencia_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transferencia_Mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bton_confirmar;
    private javax.swing.JButton bton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_montomail;
    // End of variables declaration//GEN-END:variables

    
public void transferir_dinero(JTextField txt_mail, JTextField txt_monto_mail) throws SQLException{
  ///////////variables///////////////////
    String amount = txt_montomail.getText();
  conexion.coneccion con= new conexion.coneccion();
  bancarios.SesionManager SessionManager= new bancarios.SesionManager();
  String password = SessionManager.getContraseña();
   PreparedStatement pstmtRestar = null;
   PreparedStatement pstmtSumar = null;
 Connection connection = null;
   ////fin de variables///////////
   
    try {
      connection =  con.ConectarBd();   
     connection.setAutoCommit(false); 
        String sqlRestar = "UPDATE datos_bancarios SET saldo = saldo - ? WHERE contraseña = ?";        
             pstmtRestar = con.ConectarBd().prepareStatement(sqlRestar);
             pstmtRestar.setDouble(1,Double.parseDouble(amount));
             pstmtRestar.setString(2,password);
              int filas= pstmtRestar.executeUpdate();
              
               if (filas == 0) {
                throw new Exception("No se encontró la cuenta de origen.");
            }
            //////DINERO TRANSFERIDO////////////////////////
            String sqlSumar = "UPDATE datos_bancarios SET saldo = saldo + ? WHERE email = ?";
            bancarios.MailManager mail= new bancarios.MailManager();
            String mail1 = txt_mail.getText();
           con.ConectarBd();
           PreparedStatement ps = null;
             pstmtSumar = connection.prepareStatement(sqlSumar);
              pstmtSumar.setDouble(1,Double.parseDouble(amount));
              pstmtSumar.setString(2, mail1);
               int filasSumadas = pstmtSumar.executeUpdate();
               
               if (filasSumadas == 0) {
                throw new Exception("No se encontró la cuenta de destino.");
               
                }
                     connection.commit();
                      JOptionPane.showMessageDialog(this, "Transferencia realizada con éxito.");
                      

    } catch (Exception e1) {
       
        
        if (connection != null) {
                try {
                   connection.rollback();
                } 
                catch (Exception e) {
                    e.printStackTrace();
                }
        
        
    }
     e1.printStackTrace();
       JOptionPane.showMessageDialog(this, "Error al realizar la transferencia: " + e1.getMessage());
        
    }finally {
            try {
                if (pstmtRestar != null) pstmtRestar.close();
                if (pstmtSumar != null) pstmtSumar.close();
                  if (connection != null) connection.close();
      
           
} catch (SQLException ex) {
                ex.printStackTrace();
            }
}

}





}


















